# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Indenfor10Minutter' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Indenfor10Minutter

  pod 'GoogleMaps'
  pod 'Firebase/Database'
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  
end

